// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_g7m12Fl4vmUat9cJ0gw7kpRaEsWsQY0',
    appId: '1:599779500636:ios:07ed7087769aaa37413c99',
    messagingSenderId: '599779500636',
    projectId: 'my-task-manager-gj',
    storageBucket: 'my-task-manager-gj.firebasestorage.app',
    iosBundleId: 'com.example.myTaskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_g7m12Fl4vmUat9cJ0gw7kpRaEsWsQY0',
    appId: '1:599779500636:ios:07ed7087769aaa37413c99',
    messagingSenderId: '599779500636',
    projectId: 'my-task-manager-gj',
    storageBucket: 'my-task-manager-gj.firebasestorage.app',
    iosBundleId: 'com.example.myTaskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBriO7VFzov83sFokTmVd7Rlu1AJb9umYU',
    appId: '1:599779500636:web:df0da614dec7754d413c99',
    messagingSenderId: '599779500636',
    projectId: 'my-task-manager-gj',
    authDomain: 'my-task-manager-gj.firebaseapp.com',
    storageBucket: 'my-task-manager-gj.firebasestorage.app',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMtRvp2rNKfMldij1KMQF2YLm0voV2CTo',
    appId: '1:599779500636:android:2579bb1b06eb8eaf413c99',
    messagingSenderId: '599779500636',
    projectId: 'my-task-manager-gj',
    storageBucket: 'my-task-manager-gj.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBriO7VFzov83sFokTmVd7Rlu1AJb9umYU',
    appId: '1:599779500636:web:df0da614dec7754d413c99',
    messagingSenderId: '599779500636',
    projectId: 'my-task-manager-gj',
    authDomain: 'my-task-manager-gj.firebaseapp.com',
    storageBucket: 'my-task-manager-gj.firebasestorage.app',
  );
}
